before_commands:
    - composer install
checks:
    php: true
filter:
    excluded_paths:
        - 'tests/*'
build:
    environment:
        php: '5.6'
    tests:
        override:
            -
                command: './run_tests.sh --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'clover'
